### ISSUE TITLE
Instalation failed

### ISSUE THREAD

**Issue by agustinmista** [eskerda/cmdbikes#1]
Hi! I`m getting some issues trying to install cmdbikes with pip:
```
Collecting cmdbikes
  Using cached cmdbikes-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8bL_kk/cmdbikes/setup.py", line 12, in <module>
        with open('HISTORY.rst', 'r') as f:
    IOError: [Errno 2] No such file or directory: 'HISTORY.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8bL_kk/cmdbikes/
```

**Comment by eskerda** [comment]
python2.7 right?

**Comment by eskerda** [comment]
There's both a missing MANIFEST.in file on `cmdbikes` and `python-citybikes`. Fixing that

**Comment by eskerda** [comment]
Issue fixed, can you try again? (doesn't matter which python version)

```
$ pip install --no-cache-dir cmdbikes
```

**Comment by agustinmista** [comment]
It is working now! Thank you!
