### ISSUE TITLE
"cmdbikes show" crashes regularly

### ISSUE THREAD

**Issue by PabloCastellano** [eskerda/cmdbikes#5]
I am using cmdbikes==0.1.6

Sometimes I get one result, sometimes I get more and sometimes I don't get any. But it crashes regularly.
Here is the stack trace:

```
$ cmdbikes show "Avinguda Diagonal"
Found network: Bicing, Barcelona (ES)
 374 - Pg. De Gràcia, 89
 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
 0 bikes               32 slots
Traceback (most recent call last):
  File "/home/pablo/.local/bin/cmdbikes", line 11, in <module>
    sys.exit(cli())
  File "/home/pablo/.local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/pablo/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/pablo/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pablo/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pablo/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/pablo/.local/lib/python2.7/site-packages/cli.py", line 139, in show
    display_station(station, geocode=geocode, use_colors=color)
  File "/home/pablo/.local/lib/python2.7/site-packages/cli.py", line 97, in display_station
    click.echo(padding + address)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by PabloCastellano** [comment]
@eskerda Any idea? I would like to give it a try and fix it myself

**Comment by eskerda** [comment]
Looking at the stacktrace, it looks like its trying to concatenate an address when there is none. The address comes from reverse geocoding, so it's a good idea to start looking in why the geocoder is not working as expected.

**Comment by eskerda** [comment]
I think google geocoder has deprecated keyless access to their API, which renders it unusable for this. I think I will just switch it to OSM, although their address formatting is a bit untidy

**Comment by PabloCastellano** [comment]
That works for me, thanks!
